// FIFA World Cup 2026 — Groups & Matches Data
const WORLD_CUP_DATA = {
  groups: {
    A: { teams: ["ארגנטינה", "קנדה", "צ'ילה", "פרו"] },
    B: { teams: ["מקסיקו", "ארה\"ב", "אורוגוואי", "פנמה"] },
    C: { teams: ["ספרד", "קרואטיה", "מרוקו", "ג'מייקה"] },
    D: { teams: ["צרפת", "אוסטריה", "בלגיה", "קאזחסטן"] },
    E: { teams: ["גרמניה", "יפן", "אוסטרליה", "כווית"] },
    F: { teams: ["פורטוגל", "טורקיה", "צ'כיה", "סלובקיה"] },
    G: { teams: ["ברזיל", "מקסיקו", "קולומביה", "אקוודור"] },
    H: { teams: ["אנגליה", "הולנד", "אירלנד", "ג'יבראלטר"] },
    I: { teams: ["איטליה", "שוויץ", "ונצואלה", "פרגוואי"] },
    J: { teams: ["דנמרק", "שוודיה", "פינלנד", "איסלנד"] },
    K: { teams: ["אורוגוואי", "סנגל", "בוליביה", "טנזניה"] },
    L: { teams: ["קוריאה", "ניגריה", "תאילנד", "ניו זילנד"] },
  },

  teams: {
    "ארגנטינה": {
      flag: "🇦🇷",
      color: "#74ACDF",
      titles: 3,
      starPlayer: "ליאונל מסי",
      coach: "ליאונל סקאלוני",
      funFact: "אלופי עולם 2022! מסי זכה בגביע החלומות שלו בקטאר.",
      strength: 95,
    },
    "ברזיל": {
      flag: "🇧🇷",
      color: "#009C3B",
      titles: 5,
      starPlayer: "ויניסיוס ג'וניור",
      coach: "דורידו",
      funFact: "5 תארים — יותר מכל קבוצה אחרת בהיסטוריה!",
      strength: 93,
    },
    "צרפת": {
      flag: "🇫🇷",
      color: "#002395",
      titles: 2,
      starPlayer: "קיליאן מבאפה",
      coach: "דידייה דשאן",
      funFact: "מבאפה — הכוכב הצעיר שהפך לאחד הטובים בעולם.",
      strength: 92,
    },
    "ספרד": {
      flag: "🇪🇸",
      color: "#AA151B",
      titles: 1,
      starPlayer: "פדרי",
      coach: "לואיס דה לה פואנטה",
      funFact: "אלופי אירופה 2024 — הדור הנוכחי מהולל ביותר.",
      strength: 90,
    },
    "אנגליה": {
      flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      color: "#003090",
      titles: 1,
      starPlayer: "ג'ודה בלינגהם",
      coach: "גארת' סאות'גייט",
      funFact: "זכו פעם אחת ב-1966 — האם 2026 יהיה השנה?",
      strength: 88,
    },
    "גרמניה": {
      flag: "🇩🇪",
      color: "#000000",
      titles: 4,
      starPlayer: "פלוריאן וירץ",
      coach: "יוליאן נגלסמן",
      funFact: "4 תארים ו-8 גמרות — המכונה הגרמנית חוזרת.",
      strength: 87,
    },
    "פורטוגל": {
      flag: "🇵🇹",
      color: "#006600",
      titles: 0,
      starPlayer: "ברונו פרננדש",
      coach: "רוברטו מרטינז",
      funFact: "אחרי עידן רונאלדו — דור חדש מוביל את פורטוגל.",
      strength: 85,
    },
    "הולנד": {
      flag: "🇳🇱",
      color: "#FF6600",
      titles: 0,
      starPlayer: "ארלינג הולנד (לא! — ון דייק)",
      coach: "רונלד קומן",
      funFact: "ה'כתומים' תמיד מגיעים רחוק — האם סוף סוף יזכו?",
      strength: 86,
    },
    "מקסיקו": {
      flag: "🇲🇽",
      color: "#006847",
      titles: 0,
      starPlayer: "הירווינג לוזאנו",
      coach: "חאבייר אגיירה",
      funFact: "מארחת 2026 — קהל הבית ינפח להם גב!",
      strength: 78,
    },
    "ארה\"ב": {
      flag: "🇺🇸",
      color: "#002868",
      titles: 0,
      starPlayer: "כריסטיאן פוליסיץ'",
      coach: "גרג ברהאלטר",
      funFact: "מארחת ראשית 2026 — כדורגל אמריקאי בעלייה!",
      strength: 76,
    },
  },

  // Opening matches (first week)
  matches: [
    { id: "m1", date: "2026-06-11", time: "21:00", home: "מקסיקו", away: "ארה\"ב", group: "B", venue: "לוס אנג'לס", homeScore: null, awayScore: null },
    { id: "m2", date: "2026-06-12", time: "18:00", home: "ארגנטינה", away: "קנדה", group: "A", venue: "מיאמי", homeScore: null, awayScore: null },
    { id: "m3", date: "2026-06-12", time: "21:00", home: "ספרד", away: "קרואטיה", group: "C", venue: "דאלאס", homeScore: null, awayScore: null },
    { id: "m4", date: "2026-06-13", time: "18:00", home: "ברזיל", away: "קולומביה", group: "G", venue: "סיאטל", homeScore: null, awayScore: null },
    { id: "m5", date: "2026-06-13", time: "21:00", home: "צרפת", away: "בלגיה", group: "D", venue: "ניו יורק", homeScore: null, awayScore: null },
    { id: "m6", date: "2026-06-14", time: "18:00", home: "גרמניה", away: "יפן", group: "E", venue: "שיקגו", homeScore: null, awayScore: null },
    { id: "m7", date: "2026-06-14", time: "21:00", home: "אנגליה", away: "הולנד", group: "H", venue: "בוסטון", homeScore: null, awayScore: null },
    { id: "m8", date: "2026-06-15", time: "18:00", home: "פורטוגל", away: "טורקיה", group: "F", venue: "פילדלפיה", homeScore: null, awayScore: null },
    { id: "m9", date: "2026-06-15", time: "21:00", home: "איטליה", away: "שוויץ", group: "I", venue: "הוסטון", homeScore: null, awayScore: null },
    { id: "m10", date: "2026-06-16", time: "21:00", home: "ארה\"ב", away: "ברזיל", group: "B/G", venue: "לוס אנג'לס", homeScore: null, awayScore: null },
  ],

  trivia: [
    { q: "כמה פעמים ברזיל זכתה במונדיאל?", options: ["3", "4", "5", "6"], answer: 2 },
    { q: "באיזו שנה ישראל השתתפה במונדיאל האחרון?", options: ["1966", "1970", "1974", "1978"], answer: 1 },
    { q: "מי הכדורגלן עם הכי הרבה גולים בהיסטוריית המונדיאל?", options: ["מסי", "רונאלדו", "מירוסלב קלוזה", "פלה"], answer: 2 },
    { q: "כמה שחקנים בכל קבוצה במגרש?", options: ["9", "10", "11", "12"], answer: 2 },
    { q: "כמה קבוצות משתתפות במונדיאל 2026?", options: ["32", "36", "48", "64"], answer: 2 },
    { q: "איזו מדינה מארחת את המונדיאל 2026?", options: ["ברזיל", "ארה\"ב בלבד", "ארה\"ב, קנדה ומקסיקו", "ספרד ופורטוגל"], answer: 2 },
    { q: "מי זכה במונדיאל האחרון (2022)?", options: ["צרפת", "ברזיל", "ארגנטינה", "גרמניה"], answer: 2 },
    { q: "כמה גולים כלכ מסי עשה במונדיאלים?", options: ["8", "11", "13", "16"], answer: 2 },
    { q: "מה שם הגביע שמוענק לזוכה המונדיאל?", options: ["גביע ריול", "גביע פיפ\"א", "גביע אלדורדו", "גביע יולס רימה"], answer: 1 },
    { q: "כמה זמן נמשכת משחק רגיל (ללא הארכות)?", options: ["80 דקות", "90 דקות", "100 דקות", "120 דקות"], answer: 1 },
  ]
};
